--- Makefile.orig	2011-10-19 02:37:52.000000000 +0200
+++ Makefile	2011-10-19 02:38:25.000000000 +0200
@@ -1,12 +1,12 @@
 VERSION=1.0
 
 CC=gcc
-CFLAGS=-Wall -Wno-pointer-sign -g
+CFLAGS=-Wall -Wno-pointer-sign -g $(EXTRACFLAGS)
 INSTALL=install
 
 # these locations seem to work for SuSE and Fedora
 # prefix = $(HOME)
-prefix = $(DESTDIR)/usr
+#prefix = $(DESTDIR)/usr
 BINDIR = $(prefix)/bin
 DATADIR = $(prefix)/share
 DESKTOPDIR = $(DATADIR)/applications
@@ -20,35 +20,16 @@
 DESKTOPFILE = $(NAME).desktop
 MANFILES = $(NAME).1
 
-# find libdivecomputer; we don't trust pkg-config here given how young
-# libdivecomputer still is - so we check /usr/local and /usr and then we
-# give up. You can override by simply setting it here
-#
-libdc-local := $(wildcard /usr/local/include/libdivecomputer/*)
-libdc-usr := $(wildcard /usr/include/libdivecomputer/*)
-
-ifneq ($(strip $(libdc-local)),)
-	LIBDIVECOMPUTERDIR = /usr/local
-	LIBDIVECOMPUTERINCLUDES = $(LIBDIVECOMPUTERDIR)/include/libdivecomputer
-	LIBDIVECOMPUTERARCHIVE = $(LIBDIVECOMPUTERDIR)/lib/libdivecomputer.a
-else ifneq ($(strip $(libdc-usr)),)
-	LIBDIVECOMPUTERDIR = /usr
-	LIBDIVECOMPUTERINCLUDES = $(LIBDIVECOMPUTERDIR)/include/libdivecomputer
-	LIBDIVECOMPUTERARCHIVE = $(LIBDIVECOMPUTERDIR)/lib/libdivecomputer.a
-else
-$(error Cannot find libdivecomputer - please edit Makefile)
-endif
-
-# Libusb-1.0 is only required if libdivecomputer was built with it.
-# And libdivecomputer is only built with it if libusb-1.0 is
-# installed. So get libusb if it exists, but don't complain
-# about it if it doesn't.
-LIBUSB = $(shell pkg-config --libs libusb-1.0 2> /dev/null)
+# I trust pkg-config with libdivecomputer, and I also don't want to statically
+# link libdivecomputer, because static linking is somewhat... cumbersome... on a
+# Mac.
+# Using libdivecomputer.dylib also means we don't need to link against libusb
+# manually.
+LIBDIVECOMPUTER = $(shell pkg-config --libs libdivecomputer)
+LIBDIVECOMPUTERCFLAGS = $(shell pkg-config --cflags libdivecomputer)
 
 LIBXML2 = $(shell xml2-config --libs)
 LIBGTK = $(shell pkg-config --libs gtk+-2.0 glib-2.0 gconf-2.0)
-LIBDIVECOMPUTERCFLAGS = -I$(LIBDIVECOMPUTERINCLUDES)
-LIBDIVECOMPUTER = $(LIBDIVECOMPUTERARCHIVE) $(LIBUSB)
 
 LIBS = $(LIBXML2) $(LIBGTK) $(LIBDIVECOMPUTER) -lpthread
 
@@ -56,6 +37,8 @@
 	parse-xml.o save-xml.o libdivecomputer.o print.o uemis.o \
 	gtk-gui.o
 
+all: $(NAME)
+
 $(NAME): $(OBJS)
 	$(CC) $(LDFLAGS) -o $(NAME) $(OBJS) $(LIBS)
 
